export const KEY_BINDINGS = 'KEY_BINDINGS';
export const AVAILABLE_FONTS = 'AVAILABLE_FONTS';
export const SETTINGS = 'SETTINGS';
export const INITIALIZED = 'INITIALIZED';

export const INITIALIZE_CLIENT = "INITIALIZE_CLIENT";
export const CHANGE_CLIENT_SETTINGS = "CHANGE_CLIENT_SETTINGS";